#!/bin/bash

export PEBBLE_ID=`bt-device -l | grep Pebble | cut -d ' ' -f3 | cut -c2-18`
export PARAMETERS=--lightblue
export SUBCOMMAND=remote
export APP_NAME=libreoffice

if [ "$1" == "-h" ] || [ "$1" == "--help" ];
then

  echo "Usage: `basename $0` [path_to_odp_file]"
  exit 0

elif [ "$1" == "-v" ] || [ "$1" == "--version" ];
then

  echo "2.0"
  exit 0

else

  p.py --pebble_id $PEBBLE_ID $PARAMETERS $SUBCOMMAND $APP_NAME $1

fi

